// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/pubsublite/v1/admin.proto

package com.google.cloud.pubsublite.proto;

public final class AdminProto {
  private AdminProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_CreateTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_CreateTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_GetTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_GetTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_GetTopicPartitionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_GetTopicPartitionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_TopicPartitions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_TopicPartitions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListTopicsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListTopicsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListTopicsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListTopicsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_UpdateTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_UpdateTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_DeleteTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_DeleteTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_CreateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_CreateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_GetSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_GetSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListSubscriptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListSubscriptionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_UpdateSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_UpdateSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_DeleteSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_DeleteSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_SeekSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_SeekSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_OperationMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_OperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_GetReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_GetReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListReservationTopicsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_ListReservationTopicsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&google/cloud/pubsublite/v1/admin.proto" +
      "\022\032google.cloud.pubsublite.v1\032\034google/api" +
      "/annotations.proto\032\027google/api/client.pr" +
      "oto\032\037google/api/field_behavior.proto\032\031go" +
      "ogle/api/resource.proto\032\'google/cloud/pu" +
      "bsublite/v1/common.proto\032#google/longrun" +
      "ning/operations.proto\032\033google/protobuf/e" +
      "mpty.proto\032 google/protobuf/field_mask.p" +
      "roto\032\037google/protobuf/timestamp.proto\"\235\001" +
      "\n\022CreateTopicRequest\0229\n\006parent\030\001 \001(\tB)\340A" +
      "\002\372A#\n!locations.googleapis.com/Location\022" +
      "5\n\005topic\030\002 \001(\0132!.google.cloud.pubsublite" +
      ".v1.TopicB\003\340A\002\022\025\n\010topic_id\030\003 \001(\tB\003\340A\002\"H\n" +
      "\017GetTopicRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037" +
      "pubsublite.googleapis.com/Topic\"R\n\031GetTo" +
      "picPartitionsRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372" +
      "A!\n\037pubsublite.googleapis.com/Topic\"*\n\017T" +
      "opicPartitions\022\027\n\017partition_count\030\001 \001(\003\"" +
      "u\n\021ListTopicsRequest\0229\n\006parent\030\001 \001(\tB)\340A" +
      "\002\372A#\n!locations.googleapis.com/Location\022" +
      "\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\"`" +
      "\n\022ListTopicsResponse\0221\n\006topics\030\001 \003(\0132!.g" +
      "oogle.cloud.pubsublite.v1.Topic\022\027\n\017next_" +
      "page_token\030\002 \001(\t\"\201\001\n\022UpdateTopicRequest\022" +
      "5\n\005topic\030\001 \001(\0132!.google.cloud.pubsublite" +
      ".v1.TopicB\003\340A\002\0224\n\013update_mask\030\002 \001(\0132\032.go" +
      "ogle.protobuf.FieldMaskB\003\340A\002\"K\n\022DeleteTo" +
      "picRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037pubsub" +
      "lite.googleapis.com/Topic\"}\n\035ListTopicSu" +
      "bscriptionsRequest\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!" +
      "\n\037pubsublite.googleapis.com/Topic\022\021\n\tpag" +
      "e_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\"P\n\036List" +
      "TopicSubscriptionsResponse\022\025\n\rsubscripti" +
      "ons\030\001 \003(\t\022\027\n\017next_page_token\030\002 \001(\t\"\317\001\n\031C" +
      "reateSubscriptionRequest\0229\n\006parent\030\001 \001(\t" +
      "B)\340A\002\372A#\n!locations.googleapis.com/Locat" +
      "ion\022C\n\014subscription\030\002 \001(\0132(.google.cloud" +
      ".pubsublite.v1.SubscriptionB\003\340A\002\022\034\n\017subs" +
      "cription_id\030\003 \001(\tB\003\340A\002\022\024\n\014skip_backlog\030\004" +
      " \001(\010\"V\n\026GetSubscriptionRequest\022<\n\004name\030\001" +
      " \001(\tB.\340A\002\372A(\n&pubsublite.googleapis.com/" +
      "Subscription\"|\n\030ListSubscriptionsRequest" +
      "\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!locations.goog" +
      "leapis.com/Location\022\021\n\tpage_size\030\002 \001(\005\022\022" +
      "\n\npage_token\030\003 \001(\t\"u\n\031ListSubscriptionsR" +
      "esponse\022?\n\rsubscriptions\030\001 \003(\0132(.google." +
      "cloud.pubsublite.v1.Subscription\022\027\n\017next" +
      "_page_token\030\002 \001(\t\"\226\001\n\031UpdateSubscription" +
      "Request\022C\n\014subscription\030\001 \001(\0132(.google.c" +
      "loud.pubsublite.v1.SubscriptionB\003\340A\002\0224\n\013" +
      "update_mask\030\002 \001(\0132\032.google.protobuf.Fiel" +
      "dMaskB\003\340A\002\"Y\n\031DeleteSubscriptionRequest\022" +
      "<\n\004name\030\001 \001(\tB.\340A\002\372A(\n&pubsublite.google" +
      "apis.com/Subscription\"\272\002\n\027SeekSubscripti" +
      "onRequest\022<\n\004name\030\001 \001(\tB.\340A\002\372A(\n&pubsubl" +
      "ite.googleapis.com/Subscription\022W\n\014named" +
      "_target\030\002 \001(\0162?.google.cloud.pubsublite." +
      "v1.SeekSubscriptionRequest.NamedTargetH\000" +
      "\022=\n\013time_target\030\003 \001(\0132&.google.cloud.pub" +
      "sublite.v1.TimeTargetH\000\"?\n\013NamedTarget\022\034" +
      "\n\030NAMED_TARGET_UNSPECIFIED\020\000\022\010\n\004TAIL\020\001\022\010" +
      "\n\004HEAD\020\002B\010\n\006target\"\032\n\030SeekSubscriptionRe" +
      "sponse\"\220\001\n\021OperationMetadata\022/\n\013create_t" +
      "ime\030\001 \001(\0132\032.google.protobuf.Timestamp\022,\n" +
      "\010end_time\030\002 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\016\n\006target\030\003 \001(\t\022\014\n\004verb\030\004 \001(\t\"\265\001\n\030Cr" +
      "eateReservationRequest\0229\n\006parent\030\001 \001(\tB)" +
      "\340A\002\372A#\n!locations.googleapis.com/Locatio" +
      "n\022A\n\013reservation\030\002 \001(\0132\'.google.cloud.pu" +
      "bsublite.v1.ReservationB\003\340A\002\022\033\n\016reservat" +
      "ion_id\030\003 \001(\tB\003\340A\002\"T\n\025GetReservationReque" +
      "st\022;\n\004name\030\001 \001(\tB-\340A\002\372A\'\n%pubsublite.goo" +
      "gleapis.com/Reservation\"{\n\027ListReservati" +
      "onsRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n!loca" +
      "tions.googleapis.com/Location\022\021\n\tpage_si" +
      "ze\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\"r\n\030ListRese" +
      "rvationsResponse\022=\n\014reservations\030\001 \003(\0132\'" +
      ".google.cloud.pubsublite.v1.Reservation\022" +
      "\027\n\017next_page_token\030\002 \001(\t\"\223\001\n\030UpdateReser" +
      "vationRequest\022A\n\013reservation\030\001 \001(\0132\'.goo" +
      "gle.cloud.pubsublite.v1.ReservationB\003\340A\002" +
      "\0224\n\013update_mask\030\002 \001(\0132\032.google.protobuf." +
      "FieldMaskB\003\340A\002\"W\n\030DeleteReservationReque" +
      "st\022;\n\004name\030\001 \001(\tB-\340A\002\372A\'\n%pubsublite.goo" +
      "gleapis.com/Reservation\"\202\001\n\034ListReservat" +
      "ionTopicsRequest\022;\n\004name\030\001 \001(\tB-\340A\002\372A\'\n%" +
      "pubsublite.googleapis.com/Reservation\022\021\n" +
      "\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\"H\n\035" +
      "ListReservationTopicsResponse\022\016\n\006topics\030" +
      "\001 \003(\t\022\027\n\017next_page_token\030\002 \001(\t2\257\036\n\014Admin" +
      "Service\022\271\001\n\013CreateTopic\022..google.cloud.p" +
      "ubsublite.v1.CreateTopicRequest\032!.google" +
      ".cloud.pubsublite.v1.Topic\"W\202\323\344\223\0029\"0/v1/" +
      "admin/{parent=projects/*/locations/*}/to" +
      "pics:\005topic\332A\025parent,topic,topic_id\022\233\001\n\010" +
      "GetTopic\022+.google.cloud.pubsublite.v1.Ge" +
      "tTopicRequest\032!.google.cloud.pubsublite." +
      "v1.Topic\"?\202\323\344\223\0022\0220/v1/admin/{name=projec" +
      "ts/*/locations/*/topics/*}\332A\004name\022\304\001\n\022Ge" +
      "tTopicPartitions\0225.google.cloud.pubsubli" +
      "te.v1.GetTopicPartitionsRequest\032+.google" +
      ".cloud.pubsublite.v1.TopicPartitions\"J\202\323" +
      "\344\223\002=\022;/v1/admin/{name=projects/*/locatio" +
      "ns/*/topics/*}/partitions\332A\004name\022\256\001\n\nLis" +
      "tTopics\022-.google.cloud.pubsublite.v1.Lis" +
      "tTopicsRequest\032..google.cloud.pubsublite" +
      ".v1.ListTopicsResponse\"A\202\323\344\223\0022\0220/v1/admi" +
      "n/{parent=projects/*/locations/*}/topics" +
      "\332A\006parent\022\273\001\n\013UpdateTopic\022..google.cloud" +
      ".pubsublite.v1.UpdateTopicRequest\032!.goog" +
      "le.cloud.pubsublite.v1.Topic\"Y\202\323\344\223\002?26/v" +
      "1/admin/{topic.name=projects/*/locations" +
      "/*/topics/*}:\005topic\332A\021topic,update_mask\022" +
      "\226\001\n\013DeleteTopic\022..google.cloud.pubsublit" +
      "e.v1.DeleteTopicRequest\032\026.google.protobu" +
      "f.Empty\"?\202\323\344\223\0022*0/v1/admin/{name=project" +
      "s/*/locations/*/topics/*}\332A\004name\022\336\001\n\026Lis" +
      "tTopicSubscriptions\0229.google.cloud.pubsu" +
      "blite.v1.ListTopicSubscriptionsRequest\032:" +
      ".google.cloud.pubsublite.v1.ListTopicSub" +
      "scriptionsResponse\"M\202\323\344\223\002@\022>/v1/admin/{n" +
      "ame=projects/*/locations/*/topics/*}/sub" +
      "scriptions\332A\004name\022\352\001\n\022CreateSubscription" +
      "\0225.google.cloud.pubsublite.v1.CreateSubs" +
      "criptionRequest\032(.google.cloud.pubsublit" +
      "e.v1.Subscription\"s\202\323\344\223\002G\"7/v1/admin/{pa" +
      "rent=projects/*/locations/*}/subscriptio" +
      "ns:\014subscription\332A#parent,subscription,s" +
      "ubscription_id\022\267\001\n\017GetSubscription\0222.goo" +
      "gle.cloud.pubsublite.v1.GetSubscriptionR" +
      "equest\032(.google.cloud.pubsublite.v1.Subs" +
      "cription\"F\202\323\344\223\0029\0227/v1/admin/{name=projec" +
      "ts/*/locations/*/subscriptions/*}\332A\004name" +
      "\022\312\001\n\021ListSubscriptions\0224.google.cloud.pu" +
      "bsublite.v1.ListSubscriptionsRequest\0325.g" +
      "oogle.cloud.pubsublite.v1.ListSubscripti" +
      "onsResponse\"H\202\323\344\223\0029\0227/v1/admin/{parent=p" +
      "rojects/*/locations/*}/subscriptions\332A\006p" +
      "arent\022\354\001\n\022UpdateSubscription\0225.google.cl" +
      "oud.pubsublite.v1.UpdateSubscriptionRequ" +
      "est\032(.google.cloud.pubsublite.v1.Subscri" +
      "ption\"u\202\323\344\223\002T2D/v1/admin/{subscription.n" +
      "ame=projects/*/locations/*/subscriptions" +
      "/*}:\014subscription\332A\030subscription,update_" +
      "mask\022\253\001\n\022DeleteSubscription\0225.google.clo" +
      "ud.pubsublite.v1.DeleteSubscriptionReque" +
      "st\032\026.google.protobuf.Empty\"F\202\323\344\223\0029*7/v1/" +
      "admin/{name=projects/*/locations/*/subsc" +
      "riptions/*}\332A\004name\022\337\001\n\020SeekSubscription\022" +
      "3.google.cloud.pubsublite.v1.SeekSubscri" +
      "ptionRequest\032\035.google.longrunning.Operat" +
      "ion\"w\202\323\344\223\002A\"</v1/admin/{name=projects/*/" +
      "locations/*/subscriptions/*}:seek:\001*\312A-\n" +
      "\030SeekSubscriptionResponse\022\021OperationMeta" +
      "data\022\343\001\n\021CreateReservation\0224.google.clou" +
      "d.pubsublite.v1.CreateReservationRequest" +
      "\032\'.google.cloud.pubsublite.v1.Reservatio" +
      "n\"o\202\323\344\223\002E\"6/v1/admin/{parent=projects/*/" +
      "locations/*}/reservations:\013reservation\332A" +
      "!parent,reservation,reservation_id\022\263\001\n\016G" +
      "etReservation\0221.google.cloud.pubsublite." +
      "v1.GetReservationRequest\032\'.google.cloud." +
      "pubsublite.v1.Reservation\"E\202\323\344\223\0028\0226/v1/a" +
      "dmin/{name=projects/*/locations/*/reserv" +
      "ations/*}\332A\004name\022\306\001\n\020ListReservations\0223." +
      "google.cloud.pubsublite.v1.ListReservati" +
      "onsRequest\0324.google.cloud.pubsublite.v1." +
      "ListReservationsResponse\"G\202\323\344\223\0028\0226/v1/ad" +
      "min/{parent=projects/*/locations/*}/rese" +
      "rvations\332A\006parent\022\345\001\n\021UpdateReservation\022" +
      "4.google.cloud.pubsublite.v1.UpdateReser" +
      "vationRequest\032\'.google.cloud.pubsublite." +
      "v1.Reservation\"q\202\323\344\223\002Q2B/v1/admin/{reser" +
      "vation.name=projects/*/locations/*/reser" +
      "vations/*}:\013reservation\332A\027reservation,up" +
      "date_mask\022\250\001\n\021DeleteReservation\0224.google" +
      ".cloud.pubsublite.v1.DeleteReservationRe" +
      "quest\032\026.google.protobuf.Empty\"E\202\323\344\223\0028*6/" +
      "v1/admin/{name=projects/*/locations/*/re" +
      "servations/*}\332A\004name\022\332\001\n\025ListReservation" +
      "Topics\0228.google.cloud.pubsublite.v1.List" +
      "ReservationTopicsRequest\0329.google.cloud." +
      "pubsublite.v1.ListReservationTopicsRespo" +
      "nse\"L\202\323\344\223\002?\022=/v1/admin/{name=projects/*/" +
      "locations/*/reservations/*}/topics\332A\004nam" +
      "e\032M\312A\031pubsublite.googleapis.com\322A.https:" +
      "//www.googleapis.com/auth/cloud-platform" +
      "B\321\001\n!com.google.cloud.pubsublite.protoB\n" +
      "AdminProtoP\001ZDgoogle.golang.org/genproto" +
      "/googleapis/cloud/pubsublite/v1;pubsubli" +
      "te\252\002\032Google.Cloud.PubSubLite.V1\312\002\032Google" +
      "\\Cloud\\PubSubLite\\V1\352\002\035Google::Cloud::Pu" +
      "bSubLite::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.cloud.pubsublite.proto.CommonProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_cloud_pubsublite_v1_CreateTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_pubsublite_v1_CreateTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_CreateTopicRequest_descriptor,
        new java.lang.String[] { "Parent", "Topic", "TopicId", });
    internal_static_google_cloud_pubsublite_v1_GetTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_pubsublite_v1_GetTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_GetTopicRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_GetTopicPartitionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_pubsublite_v1_GetTopicPartitionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_GetTopicPartitionsRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_TopicPartitions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_pubsublite_v1_TopicPartitions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_TopicPartitions_descriptor,
        new java.lang.String[] { "PartitionCount", });
    internal_static_google_cloud_pubsublite_v1_ListTopicsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_pubsublite_v1_ListTopicsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListTopicsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_pubsublite_v1_ListTopicsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_pubsublite_v1_ListTopicsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListTopicsResponse_descriptor,
        new java.lang.String[] { "Topics", "NextPageToken", });
    internal_static_google_cloud_pubsublite_v1_UpdateTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_pubsublite_v1_UpdateTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_UpdateTopicRequest_descriptor,
        new java.lang.String[] { "Topic", "UpdateMask", });
    internal_static_google_cloud_pubsublite_v1_DeleteTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_pubsublite_v1_DeleteTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_DeleteTopicRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsRequest_descriptor,
        new java.lang.String[] { "Name", "PageSize", "PageToken", });
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListTopicSubscriptionsResponse_descriptor,
        new java.lang.String[] { "Subscriptions", "NextPageToken", });
    internal_static_google_cloud_pubsublite_v1_CreateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_pubsublite_v1_CreateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_CreateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Parent", "Subscription", "SubscriptionId", "SkipBacklog", });
    internal_static_google_cloud_pubsublite_v1_GetSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_pubsublite_v1_GetSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_GetSubscriptionRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListSubscriptionsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_pubsublite_v1_ListSubscriptionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListSubscriptionsResponse_descriptor,
        new java.lang.String[] { "Subscriptions", "NextPageToken", });
    internal_static_google_cloud_pubsublite_v1_UpdateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_pubsublite_v1_UpdateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_UpdateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Subscription", "UpdateMask", });
    internal_static_google_cloud_pubsublite_v1_DeleteSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_pubsublite_v1_DeleteSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_DeleteSubscriptionRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_SeekSubscriptionRequest_descriptor,
        new java.lang.String[] { "Name", "NamedTarget", "TimeTarget", "Target", });
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_pubsublite_v1_SeekSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_SeekSubscriptionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_pubsublite_v1_OperationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_pubsublite_v1_OperationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_OperationMetadata_descriptor,
        new java.lang.String[] { "CreateTime", "EndTime", "Target", "Verb", });
    internal_static_google_cloud_pubsublite_v1_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_pubsublite_v1_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_CreateReservationRequest_descriptor,
        new java.lang.String[] { "Parent", "Reservation", "ReservationId", });
    internal_static_google_cloud_pubsublite_v1_GetReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_pubsublite_v1_GetReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_GetReservationRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_ListReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_pubsublite_v1_ListReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListReservationsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_google_cloud_pubsublite_v1_ListReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_pubsublite_v1_ListReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", "NextPageToken", });
    internal_static_google_cloud_pubsublite_v1_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_pubsublite_v1_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", "UpdateMask", });
    internal_static_google_cloud_pubsublite_v1_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_pubsublite_v1_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListReservationTopicsRequest_descriptor,
        new java.lang.String[] { "Name", "PageSize", "PageToken", });
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_pubsublite_v1_ListReservationTopicsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_ListReservationTopicsResponse_descriptor,
        new java.lang.String[] { "Topics", "NextPageToken", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.pubsublite.proto.CommonProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
