// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/pubsublite/v1/subscriber.proto

package com.google.cloud.pubsublite.proto;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.pubsublite.v1.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  java.util.List<com.google.cloud.pubsublite.proto.SequencedMessage> 
      getMessagesList();
  /**
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  com.google.cloud.pubsublite.proto.SequencedMessage getMessages(int index);
  /**
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  java.util.List<? extends com.google.cloud.pubsublite.proto.SequencedMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  com.google.cloud.pubsublite.proto.SequencedMessageOrBuilder getMessagesOrBuilder(
      int index);
}
