// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/pubsublite/v1/publisher.proto

package com.google.cloud.pubsublite.proto;

public final class PublisherProto {
  private PublisherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_InitialPublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_InitialPublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_InitialPublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_InitialPublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_MessagePublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_MessagePublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_MessagePublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_MessagePublishResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_pubsublite_v1_PublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_v1_PublishResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*google/cloud/pubsublite/v1/publisher.p" +
      "roto\022\032google.cloud.pubsublite.v1\032\'google" +
      "/cloud/pubsublite/v1/common.proto\032\027googl" +
      "e/api/client.proto\"9\n\025InitialPublishRequ" +
      "est\022\r\n\005topic\030\001 \001(\t\022\021\n\tpartition\030\002 \001(\003\"\030\n" +
      "\026InitialPublishResponse\"T\n\025MessagePublis" +
      "hRequest\022;\n\010messages\030\001 \003(\0132).google.clou" +
      "d.pubsublite.v1.PubSubMessage\"R\n\026Message" +
      "PublishResponse\0228\n\014start_cursor\030\001 \001(\0132\"." +
      "google.cloud.pubsublite.v1.Cursor\"\304\001\n\016Pu" +
      "blishRequest\022L\n\017initial_request\030\001 \001(\01321." +
      "google.cloud.pubsublite.v1.InitialPublis" +
      "hRequestH\000\022T\n\027message_publish_request\030\002 " +
      "\001(\01321.google.cloud.pubsublite.v1.Message" +
      "PublishRequestH\000B\016\n\014request_type\"\302\001\n\017Pub" +
      "lishResponse\022N\n\020initial_response\030\001 \001(\01322" +
      ".google.cloud.pubsublite.v1.InitialPubli" +
      "shResponseH\000\022N\n\020message_response\030\002 \001(\01322" +
      ".google.cloud.pubsublite.v1.MessagePubli" +
      "shResponseH\000B\017\n\rresponse_type2\313\001\n\020Publis" +
      "herService\022h\n\007Publish\022*.google.cloud.pub" +
      "sublite.v1.PublishRequest\032+.google.cloud" +
      ".pubsublite.v1.PublishResponse\"\000(\0010\001\032M\312A" +
      "\031pubsublite.googleapis.com\322A.https://www" +
      ".googleapis.com/auth/cloud-platformB\330\001\n!" +
      "com.google.cloud.pubsublite.protoB\016Publi" +
      "sherProtoP\001ZDgoogle.golang.org/genproto/" +
      "googleapis/cloud/pubsublite/v1;pubsublit" +
      "e\370\001\001\252\002\032Google.Cloud.PubSubLite.V1\312\002\032Goog" +
      "le\\Cloud\\PubSubLite\\V1\352\002\035Google::Cloud::" +
      "PubSubLite::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.cloud.pubsublite.proto.CommonProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
        });
    internal_static_google_cloud_pubsublite_v1_InitialPublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_pubsublite_v1_InitialPublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_InitialPublishRequest_descriptor,
        new java.lang.String[] { "Topic", "Partition", });
    internal_static_google_cloud_pubsublite_v1_InitialPublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_pubsublite_v1_InitialPublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_InitialPublishResponse_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_pubsublite_v1_MessagePublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_pubsublite_v1_MessagePublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_MessagePublishRequest_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_google_cloud_pubsublite_v1_MessagePublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_pubsublite_v1_MessagePublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_MessagePublishResponse_descriptor,
        new java.lang.String[] { "StartCursor", });
    internal_static_google_cloud_pubsublite_v1_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_pubsublite_v1_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_PublishRequest_descriptor,
        new java.lang.String[] { "InitialRequest", "MessagePublishRequest", "RequestType", });
    internal_static_google_cloud_pubsublite_v1_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_pubsublite_v1_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_pubsublite_v1_PublishResponse_descriptor,
        new java.lang.String[] { "InitialResponse", "MessageResponse", "ResponseType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.ClientProto.oauthScopes);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.cloud.pubsublite.proto.CommonProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
