// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/pubsublite/v1/topic_stats.proto

package com.google.cloud.pubsublite.proto;

public interface ComputeTimeCursorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.pubsublite.v1.ComputeTimeCursorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * If present, the cursor references the first message with time greater than
   * or equal to the specified target time. If such a message cannot be found,
   * the cursor will be unset (i.e. `cursor` is not present).
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.Cursor cursor = 1;</code>
   * @return Whether the cursor field is set.
   */
  boolean hasCursor();
  /**
   * <pre>
   * If present, the cursor references the first message with time greater than
   * or equal to the specified target time. If such a message cannot be found,
   * the cursor will be unset (i.e. `cursor` is not present).
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.Cursor cursor = 1;</code>
   * @return The cursor.
   */
  com.google.cloud.pubsublite.proto.Cursor getCursor();
  /**
   * <pre>
   * If present, the cursor references the first message with time greater than
   * or equal to the specified target time. If such a message cannot be found,
   * the cursor will be unset (i.e. `cursor` is not present).
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.Cursor cursor = 1;</code>
   */
  com.google.cloud.pubsublite.proto.CursorOrBuilder getCursorOrBuilder();
}
