/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/pubsublite/v1/subscriber.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.pubsublite.proto;

@com.google.protobuf.Generated
public interface MessageResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.pubsublite.v1.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  java.util.List<com.google.cloud.pubsublite.proto.SequencedMessage> getMessagesList();

  /**
   *
   *
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  com.google.cloud.pubsublite.proto.SequencedMessage getMessages(int index);

  /**
   *
   *
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  int getMessagesCount();

  /**
   *
   *
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  java.util.List<? extends com.google.cloud.pubsublite.proto.SequencedMessageOrBuilder>
      getMessagesOrBuilderList();

  /**
   *
   *
   * <pre>
   * Messages from the topic partition.
   * </pre>
   *
   * <code>repeated .google.cloud.pubsublite.v1.SequencedMessage messages = 1;</code>
   */
  com.google.cloud.pubsublite.proto.SequencedMessageOrBuilder getMessagesOrBuilder(int index);
}
