/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/pubsublite/v1/cursor.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.pubsublite.proto;

@com.google.protobuf.Generated
public interface StreamingCommitCursorRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.pubsublite.v1.StreamingCommitCursorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Initial request on the stream.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.InitialCommitCursorRequest initial = 1;</code>
   *
   * @return Whether the initial field is set.
   */
  boolean hasInitial();

  /**
   *
   *
   * <pre>
   * Initial request on the stream.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.InitialCommitCursorRequest initial = 1;</code>
   *
   * @return The initial.
   */
  com.google.cloud.pubsublite.proto.InitialCommitCursorRequest getInitial();

  /**
   *
   *
   * <pre>
   * Initial request on the stream.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.InitialCommitCursorRequest initial = 1;</code>
   */
  com.google.cloud.pubsublite.proto.InitialCommitCursorRequestOrBuilder getInitialOrBuilder();

  /**
   *
   *
   * <pre>
   * Request to commit a new cursor value.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.SequencedCommitCursorRequest commit = 2;</code>
   *
   * @return Whether the commit field is set.
   */
  boolean hasCommit();

  /**
   *
   *
   * <pre>
   * Request to commit a new cursor value.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.SequencedCommitCursorRequest commit = 2;</code>
   *
   * @return The commit.
   */
  com.google.cloud.pubsublite.proto.SequencedCommitCursorRequest getCommit();

  /**
   *
   *
   * <pre>
   * Request to commit a new cursor value.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.v1.SequencedCommitCursorRequest commit = 2;</code>
   */
  com.google.cloud.pubsublite.proto.SequencedCommitCursorRequestOrBuilder getCommitOrBuilder();

  com.google.cloud.pubsublite.proto.StreamingCommitCursorRequest.RequestCase getRequestCase();
}
